
export const POST_TYPES = {
  FETCH_LATEST_POST_START: 'FETCH_LATEST_POST_START',
  FETCH_LATEST_POST_SUCESS: 'FETCH_LATEST_POST_SUCESS',
  FETCH_LATEST_POST_FAILURE: 'FETCH_LATEST_POST_FAILURE',
  FETCH_NEXT_POST: 'FETCH_NEXT_POST',
  SEARCH_POST_START: 'SEARCH_POST_START',
  SEARCH_POST_SUCESS: 'SEARCH_POST_SUCESS',
  SEARCH_POST_FAILURE: 'SEARCH_POST_FAILURE'
}